# Form implementation generated from reading ui file 'phmom.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 488)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 471, 451))
        self.label.setStyleSheet("background-color: rgb(12, 11, 11);")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.ph = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ph.setGeometry(QtCore.QRect(450, 480, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.ph.setFont(font)
        self.ph.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.ph.setText("")
        self.ph.setObjectName("ph")
        self.ph2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ph2.setGeometry(QtCore.QRect(120, 480, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.ph2.setFont(font)
        self.ph2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.ph2.setText("")
        self.ph2.setObjectName("ph2")
        self.ph3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ph3.setGeometry(QtCore.QRect(140, 480, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.ph3.setFont(font)
        self.ph3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.ph3.setText("")
        self.ph3.setObjectName("ph3")
        self.ph4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ph4.setGeometry(QtCore.QRect(250, 480, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.ph4.setFont(font)
        self.ph4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.ph4.setText("")
        self.ph4.setObjectName("ph4")
        self.ph5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ph5.setGeometry(QtCore.QRect(160, 480, 16, 23))
        font = QtGui.QFont()
        font.setPointSize(1)
        self.ph5.setFont(font)
        self.ph5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.ph5.setText("")
        self.ph5.setObjectName("ph5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
