# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 601)
        MainWindow.setStyleSheet("color: rgb(13, 13, 13);\n"
"background-color: rgb(16, 16, 16);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.click = QtWidgets.QPushButton(parent=self.centralwidget)
        self.click.setGeometry(QtCore.QRect(260, 440, 141, 61))
        self.click.setStyleSheet("color: rgb(255, 255, 255);")
        self.click.setObjectName("click")
        
        self.click.raise_()
        # self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.click.setText(_translate("MainWindow", "click her "))
        # self.label.setText(_translate("MainWindow", "don\'t set her ya hywan (￣m￣）"))
