# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 397)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 601, 291))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("2- Valley Wallpaper"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.st = QtWidgets.QPushButton(self.centralwidget)
        self.st.setGeometry(QtCore.QRect(14, 310, 251, 41))
        self.st.setObjectName("st")
        self.nd = QtWidgets.QPushButton(self.centralwidget)
        self.nd.setGeometry(QtCore.QRect(340, 310, 241, 41))
        self.nd.setObjectName("nd")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
        self.st.clicked.connect(self.show1stphoto)
        self.nd.clicked.connect(self.show2ndphoto)
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.st.setText(_translate("MainWindow", "1st"))
        self.nd.setText(_translate("MainWindow", "2nd"))

    def show1stphoto(self):
        self.photo.setPixmap(QtGui.QPixmap("Wallpaper And Links/2- Valley Wallpaper"))

    def show2ndphoto(self):
        self.photo.setPixmap(QtGui.QPixmap("Wallpaper And Links/3- FiewWatch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())